package com.study.shiro.service.impl;

import com.study.shiro.domain.MenuRoleDto;
import com.study.shiro.domain.MenuRoleSearch;
import com.study.shiro.entity.MenuRole;
import com.study.shiro.entity.MenuRoleExample;
import com.study.shiro.service.MenuRoleService;
import com.study.shiro.dao.MenuRoleDao;
import org.springframework.stereotype.Service;
import javax.annotation.Resource;
import java.util.List;
import java.util.ArrayList;
import org.springframework.beans.BeanUtils;
/**
*  generated by AddClassPlugin plugin
*/

@Service
public class MenuRoleServiceImpl implements MenuRoleService {

    @Resource
    private MenuRoleDao menuRoleDao;

    @Override
    public void addMenuRole(MenuRoleDto menuRoleDto) {
        MenuRole menuRole = dtoToEntity(menuRoleDto);
        menuRoleDao.insert(menuRole);
    }

    @Override
    public void updateByMenuRoleSearch(MenuRoleDto menuRoleDto, MenuRoleSearch menuRoleSearch) {

    }

    @Override
    public MenuRoleDto findById(Integer id) {
        MenuRole menuRole = menuRoleDao.selectByPrimaryKey(id);
        return menuRole == null ? null : entityToDto(menuRole);
    }

    @Override
    public List<MenuRoleDto> searchByMenuRoleSearch(MenuRoleSearch menuRoleSearch) {
        List<MenuRoleDto> menuRoleDtos = new ArrayList<>();
        if(menuRoleSearch != null){
            MenuRoleExample menuRoleExample = getSearchExample(menuRoleSearch);

            menuRoleExample.setOrderByClause(menuRoleSearch.getOrderByClause());
            List<MenuRole> menuRoles = menuRoleDao.selectByExample(menuRoleExample);
            menuRoles.forEach(menuRole -> menuRoleDtos.add(entityToDto(menuRole)));
        }
        return menuRoleDtos;
    }

    @Override
    public Long count(MenuRoleSearch menuRoleSearch) {
        MenuRoleExample menuRoleExample = getSearchExample(menuRoleSearch);
        return menuRoleDao.countByExample(menuRoleExample);
    }

    /**
    * 查询条件设置
    * @param menuRoleSearch
    * @return
    */
    private MenuRoleExample getSearchExample(MenuRoleSearch menuRoleSearch){
        MenuRoleExample menuRoleExample = new MenuRoleExample();
        MenuRoleExample.Criteria criteria = menuRoleExample.createCriteria();
        if(menuRoleSearch ==null){
            return menuRoleExample;
        }
        if(!menuRoleSearch.getRoleIds().isEmpty()){
            criteria.andRidIn(menuRoleSearch.getRoleIds());
        }
        return menuRoleExample;
    }


    /**
    * entity to dto
    * @param menuRole
    * @return
    */
    private MenuRoleDto entityToDto(MenuRole menuRole){
        MenuRoleDto menuRoleDto = new MenuRoleDto();
        BeanUtils.copyProperties(menuRole, menuRoleDto);
        return menuRoleDto;
    }

    /**
    * dto to entity
    * @param menuRoleDto
    * @return
    */
    private MenuRole dtoToEntity(MenuRoleDto menuRoleDto){
        MenuRole menuRole = new MenuRole();
        BeanUtils.copyProperties(menuRoleDto, menuRole);
        return menuRole;
    }

}