package com.study.shiro.entity;

import java.io.Serializable;
import lombok.Data;

@Data
public class MenuRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_role.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.id
     *
     * @return the value of menu_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.id
     *
     * @param id the value for menu_role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.mid
     *
     * @return the value of menu_role.mid
     *
     * @mbg.generated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.mid
     *
     * @param mid the value for menu_role.mid
     *
     * @mbg.generated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_role.rid
     *
     * @return the value of menu_role.rid
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_role.rid
     *
     * @param rid the value for menu_role.rid
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}