package com.study.shiro.service;

import com.study.shiro.domain.HrDto;
import com.study.shiro.domain.HrSearch;
import com.study.shiro.entity.Hr;
import java.util.List;
/**
*  generated by AddClassPlugin plugin
*/

public interface HrService {
        /**
        * 新增
        * @param hrDto
        */
        void addHr(HrDto hrDto);
        /**
        * 修改(删除)
        * @param hrDto
        * @param hrSearch
        */
        void updateByHrSearch(HrDto hrDto, HrSearch hrSearch);
        /**
        * 根据id查询
        * @param id
        * @return
        */
        HrDto findById(Integer id);
        /**
        * 分页list
        * @param hrSearch
        * @return
        */
        List<HrDto> searchByHrSearch(HrSearch hrSearch);
        /**
        * 分页条数
        * @param hrSearch
        * @return
        */
        Long count(HrSearch hrSearch);

        /**
         * 根据用户名获取用户
         * @param userName
         * @return
         */
        HrDto findByName(String userName);
}