package com.study.shiro.service;

import com.study.shiro.domain.MenuRoleDto;
import com.study.shiro.domain.MenuRoleSearch;
import com.study.shiro.entity.MenuRole;
import java.util.List;
/**
*  generated by AddClassPlugin plugin
*/

public interface MenuRoleService {
        /**
        * 新增
        * @param menuRoleDto
        */
        void addMenuRole(MenuRoleDto menuRoleDto);
        /**
        * 修改(删除)
        * @param menuRoleDto
        * @param menuRoleSearch
        */
        void updateByMenuRoleSearch(MenuRoleDto menuRoleDto, MenuRoleSearch menuRoleSearch);
        /**
        * 根据id查询
        * @param id
        * @return
        */
        MenuRoleDto findById(Integer id);
        /**
        * 分页list
        * @param menuRoleSearch
        * @return
        */
        List<MenuRoleDto> searchByMenuRoleSearch(MenuRoleSearch menuRoleSearch);
        /**
        * 分页条数
        * @param menuRoleSearch
        * @return
        */
        Long count(MenuRoleSearch menuRoleSearch);
}