package com.study.shiro.service;

import com.study.shiro.domain.RoleDto;
import com.study.shiro.domain.RoleSearch;
import com.study.shiro.entity.Role;
import java.util.List;
/**
*  generated by AddClassPlugin plugin
*/

public interface RoleService {
        /**
        * 新增
        * @param roleDto
        */
        void addRole(RoleDto roleDto);
        /**
        * 修改(删除)
        * @param roleDto
        * @param roleSearch
        */
        void updateByRoleSearch(RoleDto roleDto, RoleSearch roleSearch);
        /**
        * 根据id查询
        * @param id
        * @return
        */
        RoleDto findById(Integer id);
        /**
        * 分页list
        * @param roleSearch
        * @return
        */
        List<RoleDto> searchByRoleSearch(RoleSearch roleSearch);
        /**
        * 分页条数
        * @param roleSearch
        * @return
        */
        Long count(RoleSearch roleSearch);
}