package com.study.shiro.domain;
import com.study.shiro.entity.Hr;
import com.study.shiro.entity.HrRole;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.List;

/**
*  generated by AddClassPlugin plugin
*/
@Data
@EqualsAndHashCode(callSuper=false)
public class HrDto extends Hr {
    /**
     * 角色权限
     */
    private List<RoleDto> roleList;
    /**
     * 菜单权限
     */
    private List<MenuDto> menuDtoList;
}