package com.study.shiro.domain;
import lombok.Data;
import lombok.EqualsAndHashCode;
/**
*  generated by AddClassPlugin plugin
*/
@Data
@EqualsAndHashCode(callSuper=false)
public class HrRoleSearch extends BaseSearch {

    private Integer hrId;
}