package com.study.shiro.domain;
import com.study.shiro.entity.Menu;
import lombok.Data;
import lombok.EqualsAndHashCode;
/**
*  generated by AddClassPlugin plugin
*/
@Data
@EqualsAndHashCode(callSuper=false)
public class MenuDto extends Menu {
}