package com.study.shiro.domain;
import com.study.shiro.entity.MenuRole;
import lombok.Data;
import lombok.EqualsAndHashCode;
/**
*  generated by AddClassPlugin plugin
*/
@Data
@EqualsAndHashCode(callSuper=false)
public class MenuRoleDto extends MenuRole {
}