package com.study.shiro.domain;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.List;

/**
*  generated by AddClassPlugin plugin
*/
@Data
@EqualsAndHashCode(callSuper=false)
public class RoleSearch extends BaseSearch {

    private List<Integer> ids;
}