package com.study.shiro.dao;

import com.study.shiro.entity.HrRole;
import com.study.shiro.entity.HrRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface HrRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    long countByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    int deleteByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    int insert(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    int insertSelective(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    List<HrRole> selectByExample(HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    HrRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HrRole record, @Param("example") HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HrRole record, @Param("example") HrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HrRole record);
}