package com.study.shiro.controller;

import com.study.common.response.PageResponse;
import com.study.common.response.Response;
import com.study.shiro.domain.HrDto;
import com.study.shiro.domain.HrSearch;
import com.study.shiro.service.HrService;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import javax.annotation.Resource;
import java.util.List;

/**
*  generated by AddClassPlugin plugin
*/

@RestController
public class HrController extends BaseController {

    @Resource
    private HrService hrService;
    /**
    * 新增
    * @param hrDto
    * @return
    */
    @PostMapping("/add")
    public Response addHr(@RequestBody HrDto hrDto) {
        hrService.addHr(hrDto);
        return success(Boolean.TRUE);
    }

    /**
     * 分页查询
     * @param hrSearch
     * @return
     */
    @PostMapping("get/hr/list")
    public PageResponse getHrList(@RequestBody HrSearch hrSearch) {
        List<HrDto> hrDtos = hrService.searchByHrSearch(hrSearch);
        PageResponse pageResponse = new PageResponse();
        pageResponse.rows(hrDtos);
        if (hrSearch.getPageNum() != null && hrSearch.getPageSize() != null) {
            Long count = hrService.count(hrSearch);
            pageResponse.setTotal(count);
        }
        return pageResponse;
    }

}