package com.study.shiro.controller;

import com.study.shiro.domain.MenuDto;
import com.study.shiro.service.MenuService;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import javax.annotation.Resource;
import com.study.common.response.Response;
/**
*  generated by AddClassPlugin plugin
*/

@RestController
public class MenuController extends BaseController {

    @Resource
    private MenuService menuService;
    /**
    * 新增
    * @param menuDto
    * @return
    */
    @PostMapping("nu/add")
    public Response addMenu(@RequestBody MenuDto menuDto) {
        menuService.addMenu(menuDto);
        return success(Boolean.TRUE);
    }

}