package com.study.shiro.controller;

import com.study.shiro.domain.MenuRoleDto;
import com.study.shiro.service.MenuRoleService;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import javax.annotation.Resource;
import com.study.common.response.Response;
/**
*  generated by AddClassPlugin plugin
*/

@RestController
public class MenuRoleController extends BaseController {

    @Resource
    private MenuRoleService menuRoleService;
    /**
    * 新增
    * @param menuRoleDto
    * @return
    */
    @PostMapping("nurole/add")
    public Response addMenuRole(@RequestBody MenuRoleDto menuRoleDto) {
        menuRoleService.addMenuRole(menuRoleDto);
        return success(Boolean.TRUE);
    }

}