package com.study.shiro.controller;

import com.study.shiro.domain.RoleDto;
import com.study.shiro.service.RoleService;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import javax.annotation.Resource;
import com.study.common.response.Response;
/**
*  generated by AddClassPlugin plugin
*/

@RestController
public class RoleController extends BaseController {

    @Resource
    private RoleService roleService;
    /**
    * 新增
    * @param roleDto
    * @return
    */
    @PostMapping("le/add")
    public Response addRole(@RequestBody RoleDto roleDto) {
        roleService.addRole(roleDto);
        return success(Boolean.TRUE);
    }

}